---
# tasks file for ntp
# NTP

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: install ntp
  apt:
    name=ntp
    state=present 
  changed_when: true

- name: start ntp
  service: name=ntp state=started enabled=true

- name: setup ntp server
  ansible.builtin.lineinfile:
    path: /etc/ntp.conf
    regexp: '^ Specify one or more NTP servers'
    insertafter: '^# Specify one or more NTP servers' 
    line: 3.de.pool.ntp.org iburst
    state: present
  notify: restart ntp
